### ISSUE TITLE
Transfer to the community?

### ISSUE THREAD

**Issue by majormoses** [x70b1/check_routeros-upgrade#2]
Hello I am a maintainer of https://github.com/sensu-plugins any chance you might want to open an issue and transfer this over to the community?

If you are interested you can read about the process here: https://github.com/sensu-plugins/community/blob/master/TRANSFERRING_REPOS.md and create an issue here: https://github.com/sensu-plugins/community/issues/new to start the process to transfer it over.

If you would prefer we can create a new plugin from the skel and you can just PR in the scripts if that is better as we would probably rename the repo to be consistent naming wise anyways.

**Comment by x70b1** [comment]
Hi majormoses

thanks for your request. I like idea to share the plugin to the sensu community.

At the moment this plugin is only a shell script. The sensu-plugins are Ruby only?
I don't want to rewrite the plugin at the moment.

**Comment by majormoses** [comment]
The plugins are packaged as gems but the checks, handlers, mutators can be written in any language. The only current restriction is extensions must be part be in ruby (because otherwise it needs to fork which makes it no longer an extension). If you want an example you can look at how we wrap shell scripts here: https://github.com/sensu-plugins/sensu-plugins-memory-checks/blob/master/bin/check-memory-percent.rb I undersand it might sounds like a lot of work but I am willing to help you with much of the heavy lifting. If you would like I can setup a plugin based on our skeleton and have you just create a PR against it to add the check (trying to make sure you get credit) and I can add any of the "binstub" stuff. I would also invite you to stay as a maintainer on that plugin as you know more about routeros than I probably ever will...

**Comment by x70b1** [comment]
Yes, nice. Sounds good!

What is the best way to transfer it? I guess it is more easy if you create a repository like `sensu-plugins-routeros` with that ruby wrapper. After that i can push the script, write the documentation to the skel and maintain it in the future.
But we can also transfer this repo.

**Comment by majormoses** [comment]
cool, I created an issue for me to do it (might not get around to it until the weekend).

**Comment by majormoses** [comment]
Sorry for the long delay but it is now released as a gem: https://rubygems.org/gems/sensu-plugins-routeros/versions/0.0.1

**Comment by majormoses** [comment]
Oh right for some reason I thought you already added it after I setup the repo. Please open up a PR to get it ovwe and I will release it again with actual checks.
